Enhance specification
jakartaee/nosql pull request #170
Opened 2024-02-19 06:52 UTC by otaviojava

# Changes

- Define the entity
- Define the basic fields
- Define the annotations
- Put sample annotation
- Include the annotations for compatibility with Jakarta Data

2024-02-20 15:46 UTC, njr-11 requested changes
Nice alignment of entity-related annotations with Jakarta Persistence.
I added a number of review comments which are mostly minor details/grammar.

2024-02-20 15:46 UTC, njr-11 commented on api/pom.xml
> +    <artifactId>jakarta.data-api</artifactId>
Probably a copy/paste error:
```suggestion
    <artifactId>jakarta.nosql-api</artifactId>
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/AttributeConverter.java
> +     * corresponding column for use by the JDBC driver: i.e., persistence providers are not expected to do
```suggestion
     * corresponding column for use by the NoSQL database: i.e., persistence providers are not expected to do
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Id.java
> +     * This value might be ignored if the NoSQL database has it keyword reserved for keys.
There is a grammar mistake here, and I'm not sure what you intended. One possibility is:
```suggestion
     * This value might be ignored if the NoSQL database has a keyword reserved for keys.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Id.java
>      String value() default "_id";
Do you really want to default the id to `_id` rather than the name of the annotated field?

2024-02-20 15:46 UTC, njr-11 commented on README.adoc
> +The annotations from the Mapping API will look familiar to Jakarta Persistence/JPA developers:
```suggestion
The annotations from the Mapping API will look familiar to Jakarta Persistence developers:
```

2024-02-20 15:46 UTC, njr-11 commented on README.adoc
>  * Annotation-oriented using JPA-like naming when it makes sense
```suggestion
* Annotation-oriented using Jakarta Persistence-like naming when it makes sense
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name equals the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name equals the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is like the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name is like the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is greater than the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name is greater than the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is greater than or equal to the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name is greater than or equal to the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is less than the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name is less than the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is less than or equal to the provided value.
```suggestion
         * Creates a delete condition where the value in the specified column name is less than or equal to the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is between the provided values.
```suggestion
         * Creates a delete condition where the value in the specified column name is between the provided values.
```

It would also be helpful if you mention whether between is inclusive or exclusive so that users know what to expect from it and what values to supply to get what they want.

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a delete condition where the specified column name is in the provided iterable values.
```suggestion
         * Creates a delete condition where the value in the specified column name is in the provided iterable values.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Add the order how the result will return based on a given column name.
```suggestion
         * Indicate the order in which results are returned for a given column name.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * @return a query with the first result defined
Did you mean the following here?
```suggestion
         * @return a query with the position of the first result defined
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name equals the provided value.
```suggestion
         * Creates a condition where the value in the specified column name equals the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is like the provided value.
```suggestion
         * Creates a condition where the value in the specified column name is like the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is greater than the provided value.
```suggestion
         * Creates a condition where the value in the specified column name is greater than the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is greater than or equal to the provided value.
```suggestion
         * Creates a condition where the value in the specified column name is greater than or equal to the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is less than the provided value.
```suggestion
         * Creates a condition where the value in the specified column name is less than the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is less than or equal to the provided value.
```suggestion
         * Creates a condition where the value in the specified column name is less than or equal to the provided value.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is between the provided values.
```suggestion
         * Creates a condition where the value in the specified column name is between the provided values.
```
I would recommend clarifying if it is inclusive or exclusive between

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Creates a condition where the specified column name is in the provided iterable values.
```suggestion
         * Creates a condition where the value in the specified column name is in the provided iterable values.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * @return a query with the first result defined
```suggestion
         * @return a query with the position of the first result defined
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Add the order of how the result will return based on a given column name.
```suggestion
         * Indicate the order in which results are returned for a given column name.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * If the query returns exactly one result, that result is returned in the Optional.
```suggestion
         * If the query returns exactly one result, that result is returned in the {@code Optional}.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * @return an Optional containing the single result of the query, if present, or empty if no result is found
```suggestion
         * @return an {@code Optional} containing the single result of the query, if present, or empty if no result is found
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * @return a query with the first result defined
```suggestion
         * @return a query with the position of the first result defined
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/QueryMapper.java
> +         * Add the order how the result will return.
```suggestion
         * Indicate the order in which results are returned.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> + * Copyright (c) 2022 Contributors to the Eclipse Foundation
```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> + * Templates are a helper class that increases productivity when performing common NoSQL operations.
```suggestion
 * {@code Template} is a helper class that increases productivity when performing common NoSQL operations.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * @throws NullPointerException if the iterable is null or any element is null.
In your other insert method with time-to-live, you listed UnsupportedOpeationException. Do you want that here as well?
```suggestion
     * @throws NullPointerException if the iterable is null or any element is null.
     * @throws UnsupportedOperationException if the database does not provide time-to-live for insert operations.

```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * @throws UnsupportedOperationException when the database does not provide TTL
What should the user expect to happen if the time-to-live is exceeded? This method doesn't specify.

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * <p>If the entity is versioned (for example, with {@code jakarta.persistence.Version} or by
Remove reference to jakarta.persistence class. Does NoSQL have an equivalent?
```suggestion
     * <p>If the entity is versioned (for example, with an annotation or by
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * <p>If the entity is versioned (for example, with {@code jakarta.persistence.Version} or by
Remove reference to jakarta.persistence class. Does NoSQL have an equivalent?
```suggestion
     * <p>If the entity is versioned (for example, with an annotation or by
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * @return the entity instance otherwise {@link Optional#empty()}
```suggestion
     * @return the entity instance, otherwise {@link Optional#empty()}
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * It starts a query using the fluent-API journey. It is a mutable and non-thread-safe instance.
```suggestion
     * Start a query using the fluent API. The return value is a mutable and non-thread-safe instance.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * It starts a query builder using the fluent-API journey. It is a mutable and non-thread-safe instance.
```suggestion
     * Start a query builder using the fluent API. The returned value is a mutable and non-thread-safe instance.
```

2024-02-20 15:46 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/package-info.java
> + * Copyright (c) 2022 Contributors to the Eclipse Foundation
```suggestion
 * Copyright (c) 2024 Contributors to the Eclipse Foundation
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +Jakarta NoSQL has support for those nine types:
```suggestion
Jakarta NoSQL has support for these nine types:
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +public record Person(@Id private UUID id, @Column private String name) {
```suggestion
public record Person(@Id UUID id, @Column String name) {
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +   @Column
```suggestion
    @Column
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +In this example, the `Employee' entity's' salary' field is annotated with `@Convert`, specifying the `MoneyConverter` class as the converter. The `MoneyConverter` class implements the `AttributeConve
```suggestion
In this example, the `Employee` entity's salary field is annotated with `@Convert`, specifying the `MoneyConverter` class as the converter. The `MoneyConverter` class implements the `AttributeConverter` interface to convert `MonetaryAmount` objects to and from their database representation.
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +    private String race;
Race is not the correct term. This should probably be breed or species.
```suggestion
    private String breed;
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +In this example, the `Animal` class serves as a mapped superclass where common attributes like `race` and `age` are defined. Subclasses, such as `Dog`, can then inherit these mappings, enabling a con
```suggestion
In this example, the `Animal` class serves as a mapped superclass where common attributes like `breed` and `age` are defined. Subclasses, such as `Dog`, can then inherit these mappings, enabling a consistent data model across entities while accommodating the flexibility of NoSQL database structures.
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +   "race": "Golden Retriever",
```suggestion
   "breed": "Golden Retriever",
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/annotations.adoc
> +In this JSON representation, the attributes `race` and `age` from the `Animal` superclass are inherited by the `Dog` entity, showcasing the application of mapped superclass mappings to its subclasses
```suggestion
In this JSON representation, the attributes `breed` and `age` from the `Animal` superclass are inherited by the `Dog` entity, showcasing the application of mapped superclass mappings to its subclasses.
```

2024-02-20 15:46 UTC, njr-11 commented on spec/src/main/asciidoc/chapters/api/entity.adoc
> +A programming model for entity classes might define an annotation that identifies a user-written class as an embeddable class. For example, Jakarta Persistence defines the annotation `jakarta.persist
```suggestion
Jakarta NoSQL defines an annotation that identifies a user-written class as an embeddable class: `jakarta.nosql.Embeddable`.
```

2024-02-20 15:55 UTC, otaviojava commented on api/src/main/java/jakarta/nosql/Id.java
>      String value() default "_id";
I want to make it as close to Jakarta Persistence as possible.
Thus, I can remove and allow the annotation by column.

2024-02-20 15:58 UTC, otaviojava commented on api/src/main/java/jakarta/nosql/Id.java
>      String value() default "_id";
But, mostly of the NoSQL database uses this "_id"

2024-02-20 17:57 UTC, dearrudam commented
@otaviojava it's nice to see annotations like `@DiscriminatorColumn` and `@DiscriminatorValue`. Both will help developers implement the single table inheritance strategy, which strategy that is commonly implemented when they're working with NoSQL databases like AWS Dynamo DB.

2024-02-21 13:39 UTC, otaviojava commented on api/src/main/java/jakarta/nosql/Template.java
> +     * @throws UnsupportedOperationException when the database does not provide TTL
@njr-11 better? I also explained what TTL is.

2024-02-21 15:00 UTC, njr-11 commented on api/src/main/java/jakarta/nosql/Template.java
> +     * @throws UnsupportedOperationException when the database does not provide TTL
Excellent, now the user will know what to expect of it. I'll mark this conversation resolved.

2024-02-21 15:30 UTC, otaviojava commented
> FYI - just in case they were missed in the large amount of comments, there are 2 very minor suggested changes pending. One is a fix to a copyright year and the other is a grammar correction.

Thank you @njr-11. I fixed it all.
There is a lot of work to do here, but with this sync with JPA, we are going on the right path.

2024-02-21 15:44 UTC, njr-11 approved these changes

2024-02-21 15:56 UTC, merged